language: python
python:
  - "2.7"
  - "3.3"

install:
  - pip install -r req.txt

before_script:
  - mkdir -p stream_test

script: nosetests --verbosity=2 --with-coverage --cover-erase --cover-package=duproxy
